### ISSUE TITLE
GhfsStorageStatistics cannot be cast ERROR

### ISSUE THREAD

**Issue by SurajAralihalli** [GoogleCloudDataproc/hadoop-connectors#1052]
**Description:**

Adding jar file through spark sql results in `java.lang.reflect.InvocationTargetException` exception. I believe this happens with any jar, I'm using a jar with hive udf. 

See the stack trace for the details:

```
ERROR SessionState: com.google.cloud.hadoop.fs.gcs.GhfsStorageStatistics cannot be cast to com.google.cloud.hadoop.fs.gcs.GhfsStorageStatistics
java.lang.ClassCastException: com.google.cloud.hadoop.fs.gcs.GhfsStorageStatistics cannot be cast to com.google.cloud.hadoop.fs.gcs.GhfsStorageStatistics
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:479)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3376)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:126)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3425)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3393)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:486)
	at org.apache.hadoop.hive.ql.util.ResourceDownloader.downloadResource(ResourceDownloader.java:103)
	at org.apache.hadoop.hive.ql.util.ResourceDownloader.resolveAndDownloadInternal(ResourceDownloader.java:88)
	at org.apache.hadoop.hive.ql.util.ResourceDownloader.resolveAndDownload(ResourceDownloader.java:74)
	at org.apache.hadoop.hive.ql.session.SessionState.resolveAndDownload(SessionState.java:1398)
	at org.apache.hadoop.hive.ql.session.SessionState.add_resources(SessionState.java:1350)
	at org.apache.hadoop.hive.ql.session.SessionState.add_resources(SessionState.java:1336)
	at org.apache.hadoop.hive.ql.processors.AddResourceProcessor.run(AddResourceProcessor.java:74)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$runHive$1(HiveClientImpl.scala:837)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:291)
	at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:224)
	at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:223)
```

**Steps to reproduce:**

1. Create a dataproc2.0 instance with Debian 10 
2. Open a pyspark shell `./$SPARK_HOME/pyspark`
3. Run the following script

```
import pyspark

spark = pyspark.sql.SparkSession.builder \
    .appName('adding jar spark sql') \
    .getOrCreate();

spark.sql("ADD JAR 'gs://bucket-name/hiveudf.jar'")
```

**Comment by SurajAralihalli** [comment]
Analysis from Gera:

It can be reproduced with the vanilla debian10 image without any init scripts installing rapids
1. Starting a single node cluster, this currently boils down to the image version 2.0.75-debian10
2. gcloud ssh to the master node .

create a test.py file just adding some jar via SQL
import pyspark

```
spark = pyspark.sql.SparkSession.builder \
    .appName('adding jar spark sql') \
    .getOrCreate();

spark.sql("ADD JAR 'gs://bucket-name/hiveudf.jar'")
```
 submit it even in the local mode, and we see the exception
```
gshegalov_nvidia_com@gshegalov-single-node-without-rapids-m:~$ spark-submit --master local[1] test.py 

23/09/13 17:08:35 INFO org.apache.hadoop.hive.ql.util.ResourceDownloader: converting to local gs://saralihalli/walmart-udf/hiveudf-nvbug-4258809-1.0-SNAPSHOT.jar
23/09/13 17:08:36 ERROR SessionState: com.google.cloud.hadoop.fs.gcs.GhfsStorageStatistics cannot be cast to com.google.cloud.hadoop.fs.gcs.GhfsStorageStatistics
java.lang.ClassCastException: com.google.cloud.hadoop.fs.gcs.GhfsStorageStatistics cannot be cast to com.google.cloud.hadoop.fs.gcs.GhfsStorageStatistics
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:479)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3376)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:126)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3425)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3393)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:486)
	at org.apache.hadoop.hive.ql.util.ResourceDownloader.downloadResource(ResourceDownloader.java:103)
	at org.apache.hadoop.hive.ql.util.ResourceDownloader.resolveAndDownloadInternal(ResourceDownloader.java:88)
	at org.apache.hadoop.hive.ql.util.ResourceDownloader.resolveAndDownload(ResourceDownloader.java:74)
	at org.apache.hadoop.hive.ql.session.SessionState.resolveAndDownload(SessionState.java:1398)
	at org.apache.hadoop.hive.ql.session.SessionState.add_resources(SessionState.java:1350)
	at org.apache.hadoop.hive.ql.session.SessionState.add_resources(SessionState.java:1336)
	at org.apache.hadoop.hive.ql.processors.AddResourceProcessor.run(AddResourceProcessor.java:74)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$runHive$1(HiveClientImpl.scala:837)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:291)
	at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:224)
	at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:223)
	at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:273)
	at org.apache.spark.sql.hive.client.HiveClientImpl.runHive(HiveClientImpl.scala:799)
	at org.apache.spark.sql.hive.client.HiveClientImpl.runSqlHive(HiveClientImpl.scala:786)
	at org.apache.spark.sql.hive.client.HiveClientImpl.addJar(HiveClientImpl.scala:946)
	at org.apache.spark.sql.hive.HiveSessionResourceLoader.addJar(HiveSessionStateBuilder.scala:127)
	at org.apache.spark.sql.execution.command.AddJarCommand.run(resources.scala:40)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:79)
	at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:228)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3700)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3698)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:228)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
```

Running the same command via spark-sql works fine
```
gshegalov_nvidia_com@gshegalov-single-node-without-rapids-m:~$ spark-sql --master local[1] -e "ADD JAR 'gs://bucket-name/hiveudf.jar'"
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
ivysettings.xml file not found in HIVE_HOME or HIVE_CONF_DIR,/etc/hive/conf.dist/ivysettings.xml will be used
23/09/13 17:16:47 INFO org.apache.spark.SparkEnv: Registering MapOutputTracker
23/09/13 17:16:47 INFO org.apache.spark.SparkEnv: Registering BlockManagerMaster
23/09/13 17:16:47 INFO org.apache.spark.SparkEnv: Registering BlockManagerMasterHeartbeat
23/09/13 17:16:47 INFO org.apache.spark.SparkEnv: Registering OutputCommitCoordinator
Spark master: local[1], Application Id: local-1694625408054
ADD JAR gs://saralihalli/walmart-udf/hiveudf-nvbug-4258809-1.0-SNAPSHOT.jar
23/09/13 17:16:54 WARN org.apache.hadoop.hive.ql.session.SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.
Added [/tmp/95929196-29a0-4dc0-b900-1a83a8b0d04d_resources/hiveudf-nvbug-4258809-1.0-SNAPSHOT.jar] to class path
Added resources: [gs://bucket-name/hiveudf.jar]
Time taken: 3.101 seconds
```

adding the jar outside spark.sql works around the issue
```
import pyspark

spark = pyspark.sql.SparkSession.builder \
    .appName('adding jar spark sql') \
    .getOrCreate();

spark.sparkContext._jsc.addJar('gs://bucket-name/hiveudf.jar')

spark.sql("""
CREATE TEMPORARY FUNCTION testUDF AS 'org.apache.hadoop.hive.ql.udf.generic.GenericUDFAbs';
""")

spark.sql("""
CREATE OR REPLACE TEMP VIEW test_table
  AS SELECT * FROM VALUES
(-123, 'row1'),
(123, 'row2'),
(-10123, 'row1'),
(-5665123, 'row2')
AS DATA(a, b);
""")

spark.sql("""
SELECT SUM(testUDF(a)), b FROM test_table GROUP BY b;
""").show()
```
 
```
gshegalov_nvidia_com@gshegalov-single-node-without-rapids-m:~$ spark-submit --master local[1] test2.py 
23/09/13 17:43:53 INFO org.apache.spark.SparkEnv: Registering MapOutputTracker
23/09/13 17:43:53 INFO org.apache.spark.SparkEnv: Registering BlockManagerMaster
23/09/13 17:43:53 INFO org.apache.spark.SparkEnv: Registering BlockManagerMasterHeartbeat
23/09/13 17:43:53 INFO org.apache.spark.SparkEnv: Registering OutputCommitCoordinator
23/09/13 17:43:53 INFO org.sparkproject.jetty.util.log: Logging initialized @2924ms to org.sparkproject.jetty.util.log.Slf4jLog
23/09/13 17:43:53 INFO org.sparkproject.jetty.server.Server: jetty-9.4.40.v20210413; built: 2021-04-13T20:42:42.668Z; git: b881a572662e1943a14ae12e7e1207989f218b74; jvm 1.8.0_382-b05
23/09/13 17:43:53 INFO org.sparkproject.jetty.server.Server: Started @3021ms
23/09/13 17:43:53 INFO org.sparkproject.jetty.server.AbstractConnector: Started ServerConnector@1277ae6{HTTP/1.1, (http/1.1)}{0.0.0.0:43423}
23/09/13 17:43:56 INFO com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl: Ignoring exception of type GoogleJsonResponseException; verified object already exists with desired state.
23/09/13 17:44:01 INFO org.apache.hadoop.hive.ql.exec.SerializationUtilities: Serializing GenericUDFAbs using kryo
23/09/13 17:44:01 INFO org.apache.hadoop.hive.ql.exec.SerializationUtilities: Serializing GenericUDFAbs using kryo
23/09/13 17:44:01 INFO org.apache.hadoop.hive.ql.exec.SerializationUtilities: Deserializing GenericUDFAbs using kryo
23/09/13 17:44:02 INFO org.apache.hadoop.hive.ql.exec.SerializationUtilities: Serializing GenericUDFAbs using kryo
23/09/13 17:44:02 INFO org.apache.hadoop.hive.ql.exec.SerializationUtilities: Serializing GenericUDFAbs using kryo
23/09/13 17:44:02 INFO org.apache.hadoop.hive.ql.exec.SerializationUtilities: Deserializing GenericUDFAbs using kryo
+---------------+----+
|sum(testUDF(a))|   b|
+---------------+----+
|        5665246|row2|
|          10246|row1|
+---------------+----+

23/09/13 17:44:02 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@1277ae6{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
```


**This issue is probably introduced by https://github.com/GoogleCloudDataproc/hadoop-connectors/pull/1005.**

**Comment by gerashegalov** [comment]
Thanks for filing the issue @SurajAralihalli

**Comment by kuhushukla** [comment]
CC: @medb , Could you help with this issue? Please feel free to call out other contributors. I merely used `git blame` to get the conversation going. :)

**Comment by mengdong** [comment]
@medb @jayadeep-jayaraman could you please help? thanks

**Comment by gerashegalov** [comment]
Maybe ping @arunkumarchacko, the creator of the PR #1005  causing `ClassCastException`

**Comment by arunkumarchacko** [comment]
Can you please confirm the version of GCS connector you are using?

This is a known issue and is fixed in 2.2.17 version of GCS connector. The latest DP image has this fix.

**Comment by SurajAralihalli** [comment]
The gcs-connector jar version used is `2.2.15`

**Comment by jayadeep-jayaraman** [comment]
@SurajAralihalli - can you pls create the cluster by passing this `--metadata=GCS_CONNECTOR_VERSION=2.2.17` and test again.

**Comment by viadea** [comment]
@jayadeep-jayaraman  will this issue be fixed out of the box instead of requiring user to use `--metadata=GCS_CONNECTOR_VERSION=2.2.17`?
