### ISSUE TITLE
Retry on 412 possible?

### ISSUE THREAD

**Issue by cbacon** [GoogleCloudDataproc/hadoop-connectors#11]
Getting a 412 Precondition Failed causes a stacktrace to be thrown; is it possible to retry or recover from this situation instead? Connector version was 1.4.1-hadoop1.

Stacktrace:
```
java.io.IOException: com.google.api.client.googleapis.json.GoogleJsonResponseException: 412 Precondition Failed 
{ 
"code" : 412, 
"errors" : [ { 
"domain" : "global", 
"location" : "If-Match", 
"locationType" : "header", 
"message" : "Precondition Failed", 
"reason" : "conditionNotMet" 
} ], 
"message" : "Precondition Failed" 
} 
at com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel.waitForCompletionAndThrowIfUploadFailed(AbstractGoogleAsyncWriteChannel.java:431)
at com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel.close(AbstractGoogleAsyncWriteChannel.java:289) 
at com.google.cloud.hadoop.gcsio.CacheSupplementedGoogleCloudStorage$1.close(CacheSupplementedGoogleCloudStorage.java:117) 
at java.nio.channels.Channels$1.close(Channels.java:178) 
at java.io.FilterOutputStream.close(FilterOutputStream.java:160) 
at com.google.cloud.hadoop.fs.gcs.GoogleHadoopOutputStream.close(GoogleHadoopOutputStream.java:121) 
at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:61) 
at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:86) 
at org.apache.hadoop.mapreduce.lib.output.TextOutputFormat$LineRecordWriter.close(TextOutputFormat.java:106) 
at org.apache.hadoop.mapreduce.lib.output.MultipleOutputs$RecordWriterWithCounter.close(MultipleOutputs.java:309) 
at org.apache.hadoop.mapreduce.lib.output.MultipleOutputs.close(MultipleOutputs.java:465) 
at com.spins.hdp.sld.FilterSld$M.cleanup(FilterSld.java:150) 
at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:148) 
at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764) 
at org.apache.hadoop.mapred.MapTask.run(MapTask.java:364) 
at org.apache.hadoop.mapred.Child$4.run(Child.java:255) 
at java.security.AccessController.doPrivileged(Native Method) 
at javax.security.auth.Subject.doAs(Subject.java:415) 
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190) 
at org.apache.hadoop.mapred.Child.main(Child.java:249) 
```

**Comment by AngusDavis** [comment]
In general, we can't retry uploads as we don't keep a copy of the stream contents locally. In this case, it appears to be in a mapper and that is hopefully able to retried.

From the stack trace, it looks like what's happening is that there are two or more processes writing to the same GCS object. When the stream is finalized, there's a check to ensure that the object hasn't been changed since we began writing (and to prevent errors in case one finalize RPC returns a 50X error followed by a second RPC that returns 200 OK - see https://github.com/GoogleCloudPlatform/bigdata-interop/blob/master/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java#L302 for details on that).

Is it expected that two or more processes are writing to the same object?

**Comment by Dima1224** [comment]
No, it was just one process writing. I see these types of errors (although usually 404 or 500) when using multiple outputs via the GCS connector. In this particular case I was writing to HDFS via Context and to GCS via MultipleOutputs.

Hadoop attempted to retry, but wasn't able to recover due to a bunch of

java.io.IOException: Object gs://spins/home/dmikhels/sld_load/exceptions_out/part-m-20185 already exists.
        at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.create(GoogleCloudStorageImpl.java:383)
        at com.google.cloud.hadoop.gcsio.CacheSupplementedGoogleCloudStorage.create(CacheSupplementedGoogleCloudStorage.java:98)
        at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.createInternal(GoogleCloudStorageFileSystem.java:254)
        at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.create(GoogleCloudStorageFileSystem.java:238)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopOutputStream.<init>(GoogleHadoopOutputStream.java:79)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.create(GoogleHadoopFileSystemBase.java:896)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:564)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:545)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:452)
        at org.apache.hadoop.mapreduce.lib.output.TextOutputFormat.getRecordWriter(TextOutputFormat.java:128)
        at org.apache.hadoop.mapreduce.lib.output.MultipleOutputs.getRecordWriter(MultipleOutputs.java:411)
        at org.apache.hadoop.mapreduce.lib.output.MultipleOutputs.write(MultipleOutputs.java:370)
        at com.spins.hdp.sld.FilterSld$M.reportRuleFailure(FilterSld.java:139)
        at com.spins.hdp.sld.FilterSld$M.runRules(FilterSld.java:128)
        at com.spins.hdp.sld.FilterSld$M.map(FilterSld.java:88)
        at com.spins.hdp.sld.FilterSld$M.map(FilterSld.java:1)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:364)
        at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
        at org.apache.hadoop.mapred.Child.main(Child.java:249)

**Comment by AngusDavis** [comment]
In the case of a single writer, it's most likely due to a first request to finalize the write failing (50x or timeout) followed by a second attempt and the second attempt fails because unbeknownst to us, the first write actually succeeded at some point.  The fact that a second map attempt then fails seems to support this. 

It is absolutely a hack, but a possible way to workaround the future map failures (and assuming that you're OK overwriting existing files):
<pre>
public class OverwritingTextFormat&lt;K, V> extends TextFormat&lt;K, V> {
  public RecordWriter&lt;K, V> getRecordWriter(TaskAttemptContext job) 
      throws IOException, InterruptedException {
    Path file = getDefaultWorkFile(job, extension);
    FileSystem fs = file.getFileSystem(conf);
    if (fs.exists(file)) {
      fs.delete(file);
    }
    return super.getRecordWriter(job);
}
</pre>

and when setting up the MultipleOutputs:
<pre>
MultipleOutputs.addNamedOutput(job, "text", OverwritingTextFormat.class, LongWritable.class, Text.class);
</pre>

A less hacky approach might be to write the multiple output files to HDFS as well and then distcp to GCS after the job completes. It'll obviously take longer, but might be worthwhile if you're uncomfortable with overwriting files. 

While we can't retry, we might be able to recover. A possible approach would be adding our own nonce to object metadata with each object write. If we encounter a 412, we can fetch the current version of the object and if we find the nonce associated with the failed write then we know that the write succeeded. I'm not yet certain where we'd hook this into the stack, but we can probably figure something out.

@dennishuo - Thoughts on the rough recovery proposal?

**Comment by Dima1224** [comment]
Thanks for the suggestion, that makes sense. I'll try it out if the problem comes up again. Looking forward to a fix from your guys' side when you can get to it.

Thanks!

**Comment by Shasidhar** [comment]
@AngusDavis Do we have a fix for this? Or we still have to go through the workaround mentioned above?
