### ISSUE TITLE
GCS connector requires storage.buckets.get permissions to list entities at the bucket root

### ISSUE THREAD

**Issue by sidseth** [GoogleCloudDataproc/hadoop-connectors#135]
The `StorageObjectAdmin` Role is not sufficient to able to use the GCS connector to perform the following operations
1) ls at the root ->` hadoop fs -ls gs://BUCKET/`
2) ls on an objet that does not exist -> `hadoop fs -ls gs://BUCKET/{INVALID_OBJECT}`

The exception is pasted further down.

The same is not the case for `gsutil`.
`gsutil ls gs://BUCKET/` and `gsutil ls gs://BUCKET/{INVALID_OBJECT}` works fine.

It looks like the connector falls back to perform a `bucket.get` operation. Creating a custom role with `storage.bucket.get` + `StorageObjectAdmin` gets the connector working properly again.

Is this intended behaviour? If so, would be nice to document.

Here's the stack trace.

```
Exception in thread "main" java.io.IOException: Multiple IOExceptions.
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageExceptions.createCompositeException(GoogleCloudStorageExceptions.java:60)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfos(GoogleCloudStorageImpl.java:1612)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.getFileInfosRaw(GoogleCloudStorageFileSystem.java:1298)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.listFileInfo(GoogleCloudStorageFileSystem.java:1077)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.listStatus(GoogleHadoopFileSystemBase.java:1329)
	at org.apache.hadoop.fs.generic.wrapper.GenericWrappedFileSystem.listStatus(GenericWrappedFileSystem.java:199)
	at com.hortonworks.TestSeek.run(TestSeek.java:89)
	at com.hortonworks.TestSeek.main(TestSeek.java:30)
	Suppressed: java.io.IOException: Error getting Bucket: : bucket: BUCKET_NAME
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.wrapException(GoogleCloudStorageImpl.java:1832)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl$11.onFailure(GoogleCloudStorageImpl.java:1575)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.json.JsonBatchCallback.onFailure(JsonBatchCallback.java:54)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.json.JsonBatchCallback.onFailure(JsonBatchCallback.java:50)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java:223)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.java:155)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:253)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.BatchHelper.flushIfPossible(BatchHelper.java:117)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.BatchHelper.flush(BatchHelper.java:130)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfos(GoogleCloudStorageImpl.java:1609)
		... 6 more
	Caused by: java.io.IOException: {"code":403,"errors":[{"domain":"global","message":"SERVICE_ACCOUNT@PROJECT.iam.gserviceaccount.com does not have storage.buckets.get access to BUCKET_NAME.","reason":"forbidden"}],"message":"SERVICE_ACCOUNT@PROJECT.iam.gserviceaccount.com does not have storage.buckets.get access to BUCKET_NAME."}
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl$11.onFailure(GoogleCloudStorageImpl.java:1573)
		... 14 more
	Suppressed: java.io.IOException: Error getting Bucket: : bucket: BUCKET_NAME
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.wrapException(GoogleCloudStorageImpl.java:1832)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl$11.onFailure(GoogleCloudStorageImpl.java:1575)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.json.JsonBatchCallback.onFailure(JsonBatchCallback.java:54)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.json.JsonBatchCallback.onFailure(JsonBatchCallback.java:50)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java:223)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.java:155)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:253)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.BatchHelper.flushIfPossible(BatchHelper.java:117)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.BatchHelper.flush(BatchHelper.java:130)
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfos(GoogleCloudStorageImpl.java:1609)
		... 6 more
	Caused by: java.io.IOException: {"code":403,"errors":[{"domain":"global","message":"SERVICE_ACCOUNT@PROJECT.iam.gserviceaccount.com does not have storage.buckets.get access to BUCKET_NAME.","reason":"forbidden"}],"message":"SERVICE_ACCOUNT@PROJECT.iam.gserviceaccount.com does not have storage.buckets.get access to BUCKET_NAME."}
		at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl$11.onFailure(GoogleCloudStorageImpl.java:1573)
		... 14 more
```

**Comment by functicons** [comment]
Yes, this is the intended behavior, see [roles/storage.objectAdmin](https://cloud.google.com/storage/docs/access-control/iam-roles) "Does not grant permission to read or edit bucket metadata".

**Comment by sidseth** [comment]
OK. What this means for end users using GCS is to create a custom role which is a combination of StorageObjectAdmin + the storage.buckets.get permission, or use the storage.admin role with conditions. Is there a better approach to limit access?

**Comment by locona** [comment]
@sidseth  @medb 
I have the same problem.
Have you made any progress?
