### ISSUE TITLE
Clarification about installation with spark

### ISSUE THREAD

**Issue by hadrienk** [GoogleCloudDataproc/hadoop-connectors#188]
Hi, 

I am trying to install the GCS connector. The documentation state: 

> Note that you do not need to configure Hadoop in order to use the GCS connector with Spark.

But I am getting the following exception: 
```
java.io.IOException: No FileSystem for scheme: gs
  at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
  at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
  at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
  at org.apache.spark.sql.execution.datasources.DataSource$.org$apache$spark$sql$execution$datasources$DataSource$$checkA
```

**Comment by medb** [comment]
Did you configure GCS connector for Spark, if yes how?

**Comment by hadrienk** [comment]
I have added the jar file to the class path and set the 
`spark.hadoop.google.cloud.auth.service.account.enable` and `spark.hadoop.google.cloud.auth.service.account.json.keyfile`. 

I am testing with the input from this PR as well https://github.com/GoogleCloudPlatform/bigdata-interop/pull/180/files

**Comment by hadrienk** [comment]
Ok, I got it working: 

```
 "spark.hadoop.fs.gs.impl": {
          "value": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS",
          "type": "string"
        },
        "spark.hadoop.google.cloud.auth.service.account.enable": {
          "value": true,
          "type": "checkbox"
        },
        "spark.hadoop.google.cloud.auth.service.account.json.keyfile": {
          "value": "/zeppelin/key.json",
          "type": "string"
        }
```
The PR is using a newer version maybe? https://github.com/GoogleCloudPlatform/bigdata-interop/pull/180/files because com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem was not found in the jar from the documentation.

**Comment by 8enmann** [comment]
I'm having the same issue. I'm using `spark-2.4.4-bin-hadoop2.7.tgz` and `gcs-connector-hadoop2-2.0.0.jar`. It seems like these are not the same version. How do I compile with my version of hadoop? Or did I miss the download link somewhere? I'm using pyspark.

I tried placing the jar in $SPARK_HOME/jars but I still got the not found exception. Then when I added `--conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --jars=spark/spark-2.4.4-bin-hadoop2.7/jars/gcs-connector-hadoop2-2.0.0.jar` to `spark-submit` I got this error:
```
File "[local path]/spark/spark-2.4.4-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o23.partitions.
: java.lang.NoClassDefFoundError: com/google/common/flogger/GoogleLogger
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.<clinit>(GoogleHadoopFileSystemBase.java:145)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:258)
        at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:229)
        at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:315)
        at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:204)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
        at org.apache.spark.api.java.JavaRDDLike$class.partitions(JavaRDDLike.scala:61)
        at org.apache.spark.api.java.AbstractJavaRDDLike.partitions(JavaRDDLike.scala:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.common.flogger.GoogleLogger
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 39 more
```

**Comment by medb** [comment]
@8enmann Are you using shaded jar? Seems that you just don't have [Flogger](https://google.github.io/flogger/) dependency on class path.

**Comment by 8enmann** [comment]
@medb I'm not sure what shaded jars are, but https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop2-latest.jar fixed my problem.

**Comment by medb** [comment]
Yes, this is a shaded jar.

Shaded jar is a library jar that includes all its dependencies, it has `-shaded` suffix in the name in the Maven repo and when you are building project:
https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/hadoop3-2.0.0/

**Comment by mohankrishna255** [comment]
@8enmann 

I am trying the same through spark-shell (local) on mac. But getting below error
Caused by: java.lang.ClassNotFoundException: com.google.common.flogger.GoogleLogger

Please help me to connect to google bucket from local spark.  
I want to try it on spark-shell CLI instead of generating code jar

**Comment by medb** [comment]
@mohankrishna255 What GCS connector JAR do you use? You can find download instructions in [Google Cloud documentation](https://cloud.google.com/dataproc/docs/concepts/connectors/cloud-storage#other_sparkhadoop_clusters).

**Comment by mohankrishna255** [comment]
@medb  , @8enmann  yes. I am using that Jar. Below are the steps i have been following. ( I want to connect to bucket through spark-scala REPL command line ...  Not through spark-submit)  . Kindly help

Step1: Launching spark-scala shell : spark-shell --jars /Users/tkma1ei/Desktop/stuff/Downloads/gcs-connector-hadoop2-latest.jar

Step2:  val conf = sc.hadoopConfiguration
             conf.set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
             conf.set("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")

Step3:  val df = spark.read.parquet("gs://test-bucket-sample/example.parquet")


I am getting below error 

java.lang.NoClassDefFoundError: com/google/common/flogger/GoogleLogger
  at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.<clinit>(GoogleHadoopFileSystemBase.java:150)
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:348)
  at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
  at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
  at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
  at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
  at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
  at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
  at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:45)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:332)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:645)
  at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:629)
  ... 49 elided
Caused by: java.lang.ClassNotFoundException: com.google.common.flogger.GoogleLogger
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by medb** [comment]
Man you attach an output of the `jar tf /Desktop/stuff/Downloads/gcs-connector-hadoop2-latest.jar` command?

**Comment by mohankrishna255** [comment]
[classes_1.txt](https://github.com/GoogleCloudDataproc/hadoop-connectors/files/4859185/classes_1.txt)

@medb Please check attached

**Comment by medb** [comment]
@mohankrishna255 This output seems to be correct.

What will happen if you will do exactly the same what you did in the https://github.com/GoogleCloudDataproc/hadoop-connectors/issues/188#issuecomment-652502022 but without specifying `--jars /Desktop/stuff/Downloads/gcs-connector-hadoop2-latest.jar` parameter when running `spark-shell`?

**Comment by mohankrishna255** [comment]
@medb 
If i dont specify jars, i am getting below error
Caused by: java.lang.NoClassDefFoundError: com/google/cloud/hadoop/gcsio/GoogleCloudStorageFileSystem
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 65 more
Caused by: java.lang.ClassNotFoundException: com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 70 more

**Comment by mohankrishna255** [comment]
Hi All
Any help on this

**Comment by medb** [comment]
@mohankrishna255 based on the debugging that we did it should work, so I suspect that somehow you use unshaded GCS connector JAR that does not have `GoogleLogger` class - you need to inspect your environment and make sure that you are using only shaded GCS connector JAR: https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/hadoop2-2.1.3/gcs-connector-hadoop2-2.1.3-shaded.jar

**Comment by oonisim** [comment]
Please update the https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/INSTALL.md for the correct installation and usage instructions.

**Comment by vhnguyenae** [comment]
Hi @mohankrishna255 , I ran into the same error like you (also for the case when I dont specify jars).
Are you able to fix the issue? If yes can you show me the way please?
