### ISSUE TITLE
NoSuchMethod: getPropsWithPrefix with connector version 2.x with hadoop 2.7.7

### ISSUE THREAD

**Issue by rasikas** [GoogleCloudDataproc/hadoop-connectors#323]
I have installed hadoop 2.7.7 and I've configured google [Cloud Storage Connector for 2.x](https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop2-latest.jar)

When I try to access anything on my cloud storage with the prefix `gs://` it throws this error

~~~
hadoop fs -ls gs://hstoragetest
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.conf.Configuration.getPropsWithPrefix(Ljava/lang/String;)Ljava/util/Map;
        at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.HadoopConfigurationProperty.lambda$getPropsWithPrefix$3(HadoopConfigurationProperty.java:106)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.HadoopConfigurationProperty.getLookupKey(HadoopConfigurationProperty.java:120)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.HadoopConfigurationProperty.getPropsWithPrefix(HadoopConfigurationProperty.java:106)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemConfiguration.getGcsOptionsBuilder(GoogleHadoopFileSystemConfiguration.java:417)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemConfiguration.getGcsFsOptionsBuilder(GoogleHadoopFileSystemConfiguration.java:379)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createGcsFs(GoogleHadoopFileSystemBase.java:1516)               at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1486)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:541)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:494)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:93)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2701)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2683)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:372)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:325)
        at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:235)
        at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:218)
        at org.apache.hadoop.fs.shell.Command.processRawArguments(Command.java:201)
        at org.apache.hadoop.fs.shell.Command.run(Command.java:165)
        at org.apache.hadoop.fs.FsShell.run(FsShell.java:287)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
        at org.apache.hadoop.fs.FsShell.main(FsShell.java:340)
~~~

for me it looks like hadoop connector is trying to use a method that's not exactly shipped with hadoop version `2.7.7` and I confirmed it by checking on the method `getPropsWithPrefix`
it's available in hadoop version [`2.8.3`](https://hadoop.apache.org/docs/r2.8.3/api/org/apache/hadoop/conf/Configuration.html#getPropsWithPrefix(java.lang.String)) but not available in [`2.7.7`](https://hadoop.apache.org/docs/r2.7.7/api/org/apache/hadoop/conf/Configuration.html)

Based on my limited understanding of hadoop, it is very much version dependent. Even when using spark, the version has to be very specific. So I wonder how google connector is just having only 3 versions 1.x, 2.x and 3.x

To confirm my theory, I setup hadoop 2.8.3 into a different directory with exact same connector and exact configuration file changes and simply created a soft link to new hadoop installation. Then when I run the `-ls` it worked without any problem

~~~
 hadoop fs -ls gs://hstoragetest
Found 2 items
drwx------   - rasika rasika          0 2020-03-11 07:31 gs://hstoragetest/input
drwx------   - rasika rasika          0 2020-03-11 07:32 gs://hstoragetest/output
~~~

Anyone here experiencing the same error, or have I done something wrong.

**Comment by medb** [comment]
We make use of this method in GCS connector 2.1.0, as a workaround you can use [GCS connector 2.0.1](https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop2-2.0.1.jar)

**Comment by medb** [comment]
Because [Hadoop 2.7.x branch is EOL](https://cwiki.apache.org/confluence/display/HADOOP/EOL+%28End-of-life%29+Release+Branches), I don't think that there is string incentive to still support it in latest GCS connector releases.

**Comment by rasikas** [comment]
Thank you I will try this version then, I think it would be better someone update this page (https://cloud.google.com/dataproc/docs/concepts/connectors/cloud-storage) with the all the version you have released, or pointing to a place where we can download them. Otherwise people will simply use those 3 versions given in the page.  

Thank you very much for the update

**Comment by medb** [comment]
Thanks for feedback, we will update this page, meanwhile you can find all the release versions [here](https://github.com/GoogleCloudDataproc/hadoop-connectors/releases).

**Comment by danking** [comment]
Is there an official versioning strategy for the Google Storage Hadoop connector? I would have expected a new minor version (2.1.0) would not introduce a backwards incompatible change. Should I be pinning to a particular minor version if I need backwards compatibility?

Thanks!

**Comment by medb** [comment]
GCS connector doesn't follow semantic versioning - you should expect breaking changes in minor releases, subminor/patch release should be backward-compatible releases.

**Comment by bquinart** [comment]
For info: Cloudera CDH5.16.2 is still based on Hadoop 2.6.0.
Expect a large portion of older Cloudera CDH users still to be on CDH 5.x.
I hit the the same problem and this issue helped resolved it (by using GCS connector 2.0.1).
Thanks!

**Comment by bachsh** [comment]
> Because [Hadoop 2.7.x branch is EOL](https://cwiki.apache.org/confluence/display/HADOOP/EOL+%28End-of-life%29+Release+Branches), I don't think that there is a strong incentive to still support it in latest GCS connector releases.

It might be, but to the best of my knowledge Apache Spark is still [built with Hadoop 2.7.4] (https://github.com/apache/spark/blob/master/pom.xml#L122), so that's a pretty big deal if you ask me.

**Comment by medb** [comment]
@bachsh Spark has [Hadoop 3 support](https://github.com/apache/spark/blob/61a6ca5d3f623c2a8b49277ac62d77bf4dbfa84f/pom.xml#L3036) too.

In what environment are you using GCS connector?

**Comment by bachsh** [comment]
@medb had to compile Spark v3.0 myself to use in Python3.8. I think what matters is what version they're going to ship it with by default, because asking people to recompile Spark in order to use GCS as storage doesn't seem reasonable to me.

Do you happen to know what they do in Google Dataproc? Do they deploy with an older GCS connector or do they use spark with Hadoop 3?

**Comment by medb** [comment]
Good point, it's reasonable to restore Hadoop 2.7 compatibility for 2.1.x branch that we are working actively now. It could be useful for on-prem use case too.

Datparoc doesn't ship pre-built OSS distributions, it builds its own distributions, including Spark and Hadoop. Latest Dataproc version ships Spark 2.4 w/ Hadoop 2.10, next Dataproc release will ship Spark 3.0 w/ Hadoop 3.2, so we don't have this issue in Dataproc.

**Comment by mpkd** [comment]
> We make use of this method in GCS connector 2.1.0, as a workaround you can use [GCS connector 2.0.1](https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop2-2.0.1.jar)

I got the same error in our on-prem HDP cluster with Hadoop 2.7.3. This gcs-connector-hadoop2-2.0.1.jar helped to mitigate that error. Thank you!

**Comment by michTalebzadeh** [comment]
well Insert into Google BigQuery from Hive fails with java.lang.NoSuchMethodError: org.apache.hadoop.conf.Configuration.getPropsWithPrefix(Ljava/lang/String;)Ljava

```
Hive version 3.1.1
Hadoop version  hadoop-3.1.1
```
Google SDK is installed and I built gcs-connector-hadoop3-2.2.0-shaded.jar. Added the jar file to Hive with

```
ADD JAR /home/hduser/jars/gcs-connector-hadoop3-2.2.0-shaded.jar;
```
Now I can do 

```
hdfs dfs -ls gs://etcbucket/hive

Found 1 items
drwx------   - hduser hduser          0 2022-03-04 16:57 gs://etcbucket/hive/test
```
I can read data from GBQ table as follows:

```
hive>  SELECT id,clustered, scattered, randomised, random_string, small_vc, op_type, from_unixtime(cast(cast(op_time as bigint)/1000 as bigint), 'yyyy-MM-dd hh:mm:ss') FROM test.randomdatabq LIMIT 2;

2       0.10000000149011612     1.0     0.0     ffxkVZQtqMnMcLRkBOzZUGxICGrcbxDuyBHkJlpobluliGGxGR                                                     2        1       2022-03-04 07:38:58
1       0.0     0.0     2.0     KZWeqhFWCEPyYngFbyBMWXaSCrUZoLgubbbPIayRnBUbHoWCFJ                                                      1       1       2022-03-04 07:38:58
```
Now the problem is that I cannot insert rows into GBQ table from Hive.

I have already created the GBQ table with id column INTEGER lowercase

My Hive table is created very simple as below
```
use test;
DROP TABLE IF EXISTS test.testmebq;
CREATE EXTERNAL TABLE test.testmebq(
       ID BIGINT
    )
STORED BY
 'com.google.cloud.hadoop.io.bigquery.hive.HiveBigQueryStorageHandler'
 TBLPROPERTIES (
 '[mapred.bq.input.dataset.id](http://mapred.bq.input.dataset.id/)'='test',
 '[mapred.bq.input.table.id](http://mapred.bq.input.table.id/)'='testme',
 '[mapred.bq.project.id](http://mapred.bq.project.id/)'='xxx',
 'mapred.bq.temp.gcs.path'='gs://tmp_storage_bucket/tmp',
 'mapred.bq.gcs.bucket'='etcbucket/hive/test'
)
;
```
So one column called id. Now trying to insert a row to GBQ from Hive table
```
hive> insert into test.testmebq values(11);
```
I get this error

```
java.lang.Exception: java.lang.NoSuchMethodError: org.apache.hadoop.conf.Configuration.getPropsWithPrefix(Ljava/lang/String;)Ljava/util/Map;
        at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522)
Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.conf.Configuration.getPropsWithPrefix(Ljava/lang/String;)Ljava/util/Map;
        at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.HadoopConfigurationProperty.lambda$getPropsWithPrefix$3(HadoopConfigurationProperty.java:106)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.HadoopConfigurationProperty.getLookupKey(HadoopConfigurationProperty.java:120)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.HadoopConfigurationProperty.getPropsWithPrefix(HadoopConfigurationProperty.java:106)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemConfiguration.getGcsOptionsBuilder(GoogleHadoopFileSystemConfiguration.java:457)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemConfiguration.getGcsFsOptionsBuilder(GoogleHadoopFileSystemConfiguration.java:411)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createGcsFs(GoogleHadoopFileSystemBase.java:1438)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1426)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:466)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2653)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.hadoop.hive.ql.io.avro.AvroContainerOutputFormat.getHiveRecordWriter(AvroContainerOutputFormat.java:79)
        at com.google.cloud.hadoop.io.bigquery.hive.WrappedBigQueryAvroOutputFormat.getHiveRecordWriter(WrappedBigQueryAvroOutputFormat.java:62)
        at org.apache.hadoop.hive.ql.io.HiveFileFormatUtils.getRecordWriter(HiveFileFormatUtils.java:297)
        at org.apache.hadoop.hive.ql.io.HiveFileFormatUtils.getHiveRecordWriter(HiveFileFormatUtils.java:282)
        at org.apache.hadoop.hive.ql.exec.FileSinkOperator.createBucketForFileIdx(FileSinkOperator.java:780)
        at org.apache.hadoop.hive.ql.exec.FileSinkOperator.createBucketFiles(FileSinkOperator.java:731)
        at org.apache.hadoop.hive.ql.exec.FileSinkOperator.closeOp(FileSinkOperator.java:1260)
        at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:733)
        at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:757)
        at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:757)
        at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:757)
        at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:757)
        at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:757)
        at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.close(ExecMapper.java:193)
        at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
        at org.apache.hadoop.hive.ql.exec.mr.ExecMapRunner.run(ExecMapRunner.java:37)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```
Is there any reason why it cannot find that class?

Thanks
