### ISSUE TITLE
Spark Job failing while writing to google storage

### ISSUE THREAD

**Issue by pandareen** [GoogleCloudDataproc/hadoop-connectors#353]
When I'm trying to save a dataframe to google storage in ORC format, while on a cluster with 50% pre-emptive workers, I'm getting this error
```
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 21 in stage 1.0 failed 4 times, most recent failure: Lost task 21.3 in stage 1.0 (TID 2105, prod-fct-fit-recommendation-consumer-spark-copy-ta-w-3.c.tf-prod-86479863.internal, executor 11): org.apache.spark.SparkException: Task failed while writing rows.
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:288)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:198)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:197)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.fs.FileAlreadyExistsException: 'gs://xxxxx/xxxx/xxxxx/xxx/table_name/.spark-staging-85f244a8-de5f-4d9b-8249-01bbb37f32eb/year=2018/month=12/day=4/hour=6/part-00021-85f244a8-de5f-4d9b-8249-01bbb37f32eb.c000.snappy.orc' already exists
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopOutputStream.createChannel(GoogleHadoopOutputStream.java:85)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopOutputStream.<init>(GoogleHadoopOutputStream.java:74)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.create(GoogleHadoopFileSystemBase.java:797)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1067)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1048)
	at org.apache.hadoop.hive.ql.io.orc.WriterImpl.getStream(WriterImpl.java:2103)
	at org.apache.hadoop.hive.ql.io.orc.WriterImpl.flushStripe(WriterImpl.java:2120)
	at org.apache.hadoop.hive.ql.io.orc.WriterImpl.checkMemory(WriterImpl.java:352)
	at org.apache.hadoop.hive.ql.io.orc.MemoryManager.notifyWriters(MemoryManager.java:168)
	at org.apache.hadoop.hive.ql.io.orc.MemoryManager.addedRow(MemoryManager.java:157)
	at org.apache.hadoop.hive.ql.io.orc.WriterImpl.addRow(WriterImpl.java:2413)
	at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat$OrcRecordWriter.write(OrcOutputFormat.java:76)
	at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat$OrcRecordWriter.write(OrcOutputFormat.java:55)
	at org.apache.spark.sql.hive.orc.OrcOutputWriter.write(OrcFileFormat.scala:253)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$DynamicPartitionWriteTask$$anonfun$execute$5.apply(FileFormatWriter.scala:563)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$DynamicPartitionWriteTask$$anonfun$execute$5.apply(FileFormatWriter.scala:530)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$DynamicPartitionWriteTask.execute(FileFormatWriter.scala:530)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:272)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:270)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1415)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:275)
	... 8 more
	Suppressed: org.apache.hadoop.fs.FileAlreadyExistsException: 'gs://xxxxx/xxxx/xxxxx/xxx/table_name/.spark-staging-85f244a8-de5f-4d9b-8249-01bbb37f32eb/year=2018/month=12/day=4/hour=6/part-00021-85f244a8-de5f-4d9b-8249-01bbb37f32eb.c000.snappy.orc' already exists
```

I am using Google dataproc with spark version 2.3

**Comment by medb** [comment]
May you test if this issue reproducible in 2 more cases:
- without preemptible workers
- with 50% preemptible workers but with writes to HDFS

**Comment by pandareen** [comment]
@medb Thanks for the comment, this is a spark bug in progress. More details https://github.com/apache/spark/pull/26339
