### ISSUE TITLE
Not able to access GCS from HDInsight cluster.

### ISSUE THREAD

**Issue by nileshpatil1992** [GoogleCloudDataproc/hadoop-connectors#435]
I am trying to access GCS from local and able to access by setting below properties in Hadoop configuration.

```scala
sparksession.sparkContext().hadoopConfiguration().set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem");
sparksession.sparkContext().hadoopConfiguration().set("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS");
sparksession.sparkContext().hadoopConfiguration().set("google.cloud.auth.service.account.enable", "true");
sparksession.sparkContext().hadoopConfiguration().set("fs.gs.project.id", "XXXX");
sparksession.sparkContext().hadoopConfiguration().set("google.cloud.auth.service.account.private.key.id", "XXXX");
sparksession.sparkContext().hadoopConfiguration().set("google.cloud.auth.service.account.private.key","XXXX");
sparksession.sparkContext().hadoopConfiguration().set("google.cloud.auth.service.account.email","XXXX");
```

 But when I am trying to access from HDInsight cluster I am getting:
```
java.io.IOException: Error getting access token from metadata server at: http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialFactory.getCredentialFromMetadataServiceAccount(CredentialFactory.java:220)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialConfiguration.getCredential(CredentialConfiguration.java:75)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1869)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:1058)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:1021)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2796)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:99)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2830)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2812)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:390)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.<init>(BigQueryWriteHelper.scala:58)
	at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:41)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:100)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:656)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:656)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:656)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:273)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:267)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:225)
	at com.lti.mosaic.connector.impl.rdbms.bigquery.BigQueryConnectorService.writeDataset(BigQueryConnectorService.java:232)
	at com.lti.mosaic.connector.external.writer.WriterService.writeDataset(WriterService.java:37)
	at com.lti.mosaic.dag.engine.source1b0f23b364ed.Untitled_3_661447.write_BIGQUERY2(Untitled_3_661447.java:270)
	at com.lti.mosaic.dag.engine.source1b0f23b364ed.Untitled_3_661447.BIGQUERY2(Untitled_3_661447.java:249)
	at com.lti.mosaic.dag.engine.source1b0f23b364ed.Untitled_3_661447.executeFlowTill(Untitled_3_661447.java:83)
	at com.lti.mosaic.dag.engine.source1b0f23b364ed.Untitled_3_661447.execute(Untitled_3_661447.java:127)
	at com.lti.mosaic.dag.engine.source1b0f23b364ed.Untitled_3_661447.main(Untitled_3_661447.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:721)
Caused by: com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpResponseException: 404 Not Found
```

**Comment by medb** [comment]
Most probably you are setting this properties too late, after Spark context already initialized. May you try to set the same properties in the `--conf` command line arguments or Spark config?

**Comment by nileshpatil1992** [comment]
@medb  I have tired to set config at the time of creating spark session also tired to set it in spark context and spark session config after creating session. But no luck. Still same issue I am getting.
SparkSession sparksession=SparkSession.builder()
		.config(new SparkConf()
		        .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
		        .set("spark.hadoop.fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
		        .set("spark.hadoop.fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")
		        .set("spark.hadoop.fs.gs.project.id", "XXXX")
		        .set("spark.hadoop.fs.gs.system.bucket", "XXXX")
		        .set("spark.hadoop.fs.gs.auth.service.account.enable", "true")
		        .set("spark.hadoop.fs.gs.auth.service.account.email", "XXXX")
		        .set("spark.hadoop.fs.gs.auth.service.account.private.key.id", "XXXX")
		        .set("spark.hadoop.fs.gs.auth.service.account.private.key", "XXXXX"))
		   //   .master("local")
		 //   .master("yarn-cluster")
		      .getOrCreate();

**Comment by medb** [comment]
I don't think that `getOrCreate` is appropriate here, because `SparkSession` could exist already and new configuration will not impact it.

May you set these options in CLI? `spark-submit` or `spark-shell` using `--conf` arguments?

```bash
spark-shell \
  --conf "spark.serializer=org.apache.spark.serializer.KryoSerializer"\
  --conf "spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem" \
  --conf "spark.hadoop.fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS" \
  --conf "spark.hadoop.fs.gs.project.id=XXXX" \
  --conf "spark.hadoop.fs.gs.system.bucket=XXXX" \
  --conf "spark.hadoop.fs.gs.auth.service.account.enable=true" \
  --conf "spark.hadoop.fs.gs.auth.service.account.email=XXXX" \
  --conf "spark.hadoop.fs.gs.auth.service.account.private.key.id=XXXX" \
  --conf "spark.hadoop.fs.gs.auth.service.account.private.key=XXXXX"
```

**Comment by nileshpatil1992** [comment]
@medb  Yes tried this as well but no luck. One this I have observed is CredentialFactory class gets loaded from below jar. thcom.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util..getCredentialFromMetadataServiceAccount()

My cluster is having hadoop 2.7.3 and I have tried gcs-connector-hadoop2-2.1.4.jar,gcs-connector-hadoop2-2.0.0.jar, gcs-connector-hadoop3-2.1.0 version. Is there any possibility because of jar conflict I am getting this issue ?

**Comment by medb** [comment]
No, jars should be fine, you should use `gcs-connector-hadoop2-2.1.4.jar` for your Hadoop version.

This exception means that configuration is not applied, and GCS connector tries to use default authentication method that works only in GCE VMs.

May you try to set the same configuration in `hadoop fs` command and post debug output for it:

```
hadoop --loglevel debug fs \
  -D "fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem" \
  -D "fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS" \
  -D "fs.gs.project.id=XXXX" \
  -D "fs.gs.auth.service.account.enable=true" \
  -D "fs.gs.auth.service.account.email=XXXX" \
  -D "fs.gs.auth.service.account.private.key.id=XXXX" \
  -D "fs.gs.auth.service.account.private.key=XXXXX"
  -ls gs://<BUCKET>
```

**Comment by nileshpatil1992** [comment]
@medb  I have tried executing command and I am getting below debug log.

20/09/02 13:34:25 DEBUG util.Shell: setsid exited with exit code 0
20/09/02 13:34:25 DEBUG conf.Configuration: parsing URL jar:file:/usr/hdp/2.6.5.3016-3/hadoop/hadoop-common-2.7.3.2.6.5.3016-3.jar!/core-default.xml
20/09/02 13:34:25 DEBUG conf.Configuration: parsing input stream sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@551bdc27
20/09/02 13:34:25 DEBUG conf.Configuration: parsing URL file:/etc/hadoop/2.6.5.3016-3/0/core-site.xml
20/09/02 13:34:25 DEBUG conf.Configuration: parsing input stream java.io.BufferedInputStream@78b1cc93
20/09/02 13:34:25 DEBUG security.SecurityUtil: Setting hadoop.security.token.service.use_ip to true
20/09/02 13:34:25 DEBUG security.Groups:  Creating new Groups object
20/09/02 13:34:25 DEBUG util.NativeCodeLoader: Trying to load the custom-built native-hadoop library...
20/09/02 13:34:25 DEBUG util.NativeCodeLoader: Loaded the native-hadoop library
20/09/02 13:34:25 DEBUG security.JniBasedUnixGroupsMapping: Using JniBasedUnixGroupsMapping for Group resolution
20/09/02 13:34:25 DEBUG security.JniBasedUnixGroupsMappingWithFallback: Group mapping impl=org.apache.hadoop.security.JniBasedUnixGroupsMapping
20/09/02 13:34:26 DEBUG security.Groups: Group mapping impl=org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback; cacheTimeout=300000; warningDeltaMs=5000
20/09/02 13:34:26 DEBUG security.UserGroupInformation: hadoop login
20/09/02 13:34:26 DEBUG security.UserGroupInformation: hadoop login commit
20/09/02 13:34:26 DEBUG security.UserGroupInformation: using local user:UnixPrincipal: mosaic
20/09/02 13:34:26 DEBUG security.UserGroupInformation: Using user: "UnixPrincipal: mosaic" with name mosaic
20/09/02 13:34:26 DEBUG security.UserGroupInformation: User entry: "mosaic"
20/09/02 13:34:26 DEBUG security.UserGroupInformation: Assuming keytab is managed externally since logged in from subject.
20/09/02 13:34:26 DEBUG security.UserGroupInformation: UGI loginUser:mosaic (auth:SIMPLE)
20/09/02 13:34:26 DEBUG gcs.GoogleHadoopFileSystemBase: GHFS version: 1.8.1.2.6.5.3016-3
20/09/02 13:34:26 DEBUG gcs.GoogleHadoopFileSystemBase: GHFS.initialize: gs://mosaicdataconnector
20/09/02 13:34:26 DEBUG gcs.GoogleHadoopFileSystemBase: GHFS.configure
20/09/02 13:34:26 DEBUG gcs.GoogleHadoopFileSystemBase: GHFS_ID = GHFS/1.8.1.2.6.5.3016-3
20/09/02 13:34:26 DEBUG util.CredentialConfiguration: Using service account credentials
20/09/02 13:34:26 DEBUG util.CredentialConfiguration: Getting service account credentials from meta data service.
20/09/02 13:34:26 DEBUG util.CredentialFactory: getCredentialFromMetadataServiceAccount()
ls: Error getting access token from metadata server at: http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token

**Comment by medb** [comment]
This log shows that you are using very old GCS connector version:

```
20/09/02 13:34:26 DEBUG gcs.GoogleHadoopFileSystemBase: GHFS version: 1.8.1.2.6.5.3016-3
```

I think that this is the version that comes pre-installed in HDInsight.

This GCS connector version does not support `fs.gs.auth.service.account.private.key.id` and `fs.gs.auth.service.account.private.key` configuration properties for authentication. You should use JSON key file for authentication instead: `fs.gs.auth.service.account.json.keyfile`.

[Here](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v1.8.1/util/src/main/java/com/google/cloud/hadoop/util/EntriesCredentialConfiguration.java#L55-L75) you can find authentication configuration options for this GCS connector version.
