### ISSUE TITLE
GCS connector should be able to make unauth'd requests to GCS public buckets

### ISSUE THREAD

**Issue by jaketf** [GoogleCloudDataproc/hadoop-connectors#459]
### Feature Request
Allow GCS connector to make un-auth'd requests to GCS (e.g. list / download file from public bucket) with minimal configuration.
This could be exposed as a new config `fs.gs.auth.none=true`. This is mostly helpful for lightweight CI and demos using public buckets.

### Use Case
When installing GCS connector in a docker image (in my case I am preparing an apache airflow image and need to use gcs connector to stage spark jars on GCS when using SparkSubmitOperator) I should be able to easily verify it's installation in CI script without having to give credentials.

For example my ci script might run :
```shell
docker run --rm "${AIRFLOW_IMAGE}"  \
  bash -c "hadoop fs -D fs.gs.auth.none=true -ls gs://gcp-public-data-landsat && GCS Connector Installation Validated!"
```

**Comment by medb** [comment]
This functionality already implemented via  `google.auth.null.enable` or `fs.gs.auth.null.enable` properties:
https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/6f266d8f0f8519363441b74881110e96c196bad7/util-hadoop/src/main/java/com/google/cloud/hadoop/util/HadoopCredentialConfiguration.java#L123

**Comment by tooptoop4** [comment]
@medb this is not working for me, I get this error with v2.0.0 libs:

```
  java.lang.IllegalArgumentException: credential must not be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.<init>(GoogleCloudStorageFileSystem.java:148)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createGcsFs(GoogleHadoopFileSystemBase.java:1604)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1554)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:553)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:506)
	at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:125)
	at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:92)
	at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:65)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
```
