### ISSUE TITLE
GCS Connector throwing exception when given path with wildcard

### ISSUE THREAD

**Issue by btusakul-sift** [GoogleCloudDataproc/hadoop-connectors#797]
I've been trying to deploy a Spark history server into GKE with a container similar to [this](https://github.com/lightbend/spark-history-server-docker). However, I'm getting this exception when using a log directory path with a wildcard character:

`
Exception in thread "main" java.io.FileNotFoundException: Log directory specified does not exist: gs://bucket-name/*/spark-job-history at org.apache.spark.deploy.history.FsHistoryProvider.startPolling(FsHistoryProvider.scala:291) at org.apache.spark.deploy.history.FsHistoryProvider.initialize(FsHistoryProvider.scala:236) at org.apache.spark.deploy.history.FsHistoryProvider.start(FsHistoryProvider.scala:413) at org.apache.spark.deploy.history.HistoryServer$.main(HistoryServer.scala:306) at org.apache.spark.deploy.history.HistoryServer.main(HistoryServer.scala) Caused by: java.io.FileNotFoundException: File not found: gs://bucket-name/*/spark-job-history at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getFileStatus(GoogleHadoopFileSystemBase.java:958) at org.apache.spark.deploy.history.FsHistoryProvider.startPolling(FsHistoryProvider.scala:281) ... 4 more
`

I can confirm that this bucket and path does exist and that the path works with `gsutil ls` commands or when configured with a Dataproc Persistent History Server  and my understanding is that [Dataproc clusters make use of this connector as well](https://cloud.google.com/dataproc/docs/concepts/connectors/cloud-storage#clusters).

I've tested this with the gcs-connector-hadoop{2,3}-2.2.6 connectors and both display the same behavior.

**Comment by medb** [comment]
For `*` in the path to be treated as a glob [`FileSystem#globStatus`](https://hadoop.apache.org/docs/stable/api/org/apache/hadoop/fs/FileSystem.html#globStatus-org.apache.hadoop.fs.Path-), not [`FileSystem.getFileStatus`](https://hadoop.apache.org/docs/stable/api/org/apache/hadoop/fs/FileSystem.html#getFileStatus-org.apache.hadoop.fs.Path-) should be used.

It seems that OSS Spark History server does not support this use case.

Please consider using Dataproc Persistent History Server that supports this use case: https://cloud.google.com/dataproc/docs/concepts/jobs/history-server
