### ISSUE TITLE
 Type `com/google/protobuf/GeneratedMessage$GeneratedExtension` (current frame, stack[1]) is not assignable to `com/google/protobuf/ExtensionLite`

### ISSUE THREAD

**Issue by sharan21** [GoogleCloudDataproc/hadoop-connectors#892]
I'm trying to write a simple script on my local machine that can read a dataset from GBQ and write the spark df onto my GCS storage bucket. The first part is working i.e. I can read from GBQ and store it as a df. However, it fails in the last line, while trying to write the df to a gs:// path. It seems like there is a dependency conflict that I am not able to solve for quite some time. I am using the 'com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.2.8' connector. This is the code:
```
from google.cloud import storage
from pyspark.sql import SparkSession
r'/Users/snarasimhan/.config/gcloud/application_default_credentials.json'


spark = SparkSession.builder.config("google.cloud.auth.service.account.enable", "true")\
.config("google.cloud.auth.service.account.json.keyfile",  "/Users/snarasimhan/.config/gcloud/application_default_credentials.json") \
.config('spark.jars.packages', 'com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.27.0,com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.2.8')\
.appName('gbqUploadTest').getOrCreate()

df = spark.read.format('bigquery').option('table','extended-cache-365509:mydataset.mytable').load()
print(df)

spark.conf.set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
df.write.csv('gs://test_bucket_sharan/upload_test')
```

It fails in the last line with the error: 
```
Traceback (most recent call last):
  File "working.py", line 20, in <module>
    df.write.csv('gs://test_bucket_sharan/upload_test')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 935, in csv
    self._jwrite.csv(path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o57.csv.
: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:134)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2668)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.spark.sql.execution.datasources.DataSource.planForWritingFileFormat(DataSource.scala:438)
	at org.apache.spark.sql.execution.datasources.DataSource.planForWriting(DataSource.scala:538)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:310)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:291)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:249)
	at org.apache.spark.sql.DataFrameWriter.csv(DataFrameWriter.scala:684)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:132)
	... 23 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/google/api/ClientProto.registerAllExtensions(Lcom/google/protobuf/ExtensionRegistryLite;)V @4: invokevirtual
  Reason:
    Type 'com/google/protobuf/GeneratedMessage$GeneratedExtension' (current frame, stack[1]) is not assignable to 'com/google/protobuf/ExtensionLite'
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'com/google/protobuf/ExtensionRegistryLite' }
    stack: { 'com/google/protobuf/ExtensionRegistryLite', 'com/google/protobuf/GeneratedMessage$GeneratedExtension' }
  Bytecode:
    0x0000000: 2ab2 0002 b600 032a b200 04b6 0003 2ab2
    0x0000010: 0005 b600 03b1

	at com.google.storage.v2.StorageProto.<clinit>(StorageProto.java:435)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageOptions.<clinit>(GoogleCloudStorageOptions.java:54)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemConfiguration.<clinit>(GoogleHadoopFileSystemConfiguration.java:356)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.<init>(GoogleHadoopFileSystemBase.java:247)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem.<init>(GoogleHadoopFileSystem.java:58)
	... 28 more
```

Any help is appreciated!

**Comment by hoanpvzz** [comment]
Same problem after test with version **_com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.2.5->8_** .
Anyone can share version can be used ?

**Comment by sharan21** [comment]
As a workaround, I found that working with gs:// works when you run spark using spark-submit. Just download the jar file from https://cloud.google.com/dataproc/docs/concepts/connectors/cloud-storage and add --files /path/to/hadoop-jar.
However working without notebooks is tedious during debugging and I am still facing the issue while trying to use notebooks as mentioned above.

**Comment by hoanpvzz** [comment]
thank for share @sharan21 
It work with many depend packages :(
```bash
spark-submit \
--packages com.google.api-client:google-api-client-jackson2:2.0.0,\
com.google.auto.value:auto-value-annotations:1.10,\
com.google.cloud.bigdataoss:util:2.2.8,\
com.google.cloud.bigdataoss:util-hadoop:1.9.4-hadoop3,\
com.google.cloud.bigdataoss:gcsio:2.2.8,\
com.google.code.gson:gson:2.10,\
com.google.flogger:flogger:0.7.4,\
com.google.flogger:google-extensions:0.7.4,\
com.google.guava:guava:31.1-jre,\
com.google.oauth-client:google-oauth-client:1.34.1 \
--jars ./gcs-connector-hadoop3-latest.jar ...
```

**Comment by medb** [comment]
You need to use a shaded GCS connector jar to avoid managing dependencies manually: https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/hadoop3-2.2.10/gcs-connector-hadoop3-2.2.10-shaded.jar
