### ISSUE TITLE
Unable to read data from public access bucket

### ISSUE THREAD

**Issue by nicojord** [GoogleCloudDataproc/hadoop-connectors#924]
Hi, we tried to write some tests for our spark implementation using public data access. I was able to hit public access data in other cloud providers fine but have issues doing the same with the gcs-connector reading public data on the google cloud platform. 

Found this config option that seemed like it might do the trick, "fs.gs.auth.type", "UNAUTHENTICATED". But this doesnt seem to work and looks like its intended to be used when running spark on internal gcs VM's.

Steps to reproduce:

        spark_conf = SparkConf() \
                                  .set("fs.gs.auth.type", "UNAUTHENTICATED") \
                                  .set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem") \
                                  .set("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS") \
                

        spark = SparkSession \
                .builder \
                .appName('test_gcs') \
                .config(conf=spark_conf) \
                .getOrCreate()

        df = spark.read.csv("gs://gcp-public-data-landsat/index.csv.gz")
        df.show()

StackTrace:

              22/12/13 11:18:49 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: gs://gcp-public-data-landsat/index.csv.gz.
              java.io.IOException: Error getting access token from metadata server at: http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token
	              at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialFactory.getCredentialFromMetadataServiceAccount(CredentialFactory.java:250)
	              at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialFactory.getCredential(CredentialFactory.java:389)
	              at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getCredential(GoogleHadoopFileSystemBase.java:1341)
	              at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createGcsFs(GoogleHadoopFileSystemBase.java:1497)
	              at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1479)
	              at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:467)
	              at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
	              at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	              at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	              at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	              at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	              at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	              at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
	              at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
	              at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
	              at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
	              at scala.Option.getOrElse(Option.scala:189)
	              at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
	              at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:537)
	              at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	              at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	              at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	              at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	              at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	              at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	              at py4j.Gateway.invoke(Gateway.java:282)
	              at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	              at py4j.commands.CallCommand.execute(CallCommand.java:79)
	              at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	              at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	              at java.base/java.lang.Thread.run(Unknown Source)
              Caused by: java.net.SocketTimeoutException: connect timed out
	              at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	              at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	              at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	              at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	              at java.base/java.net.Socket.connect(Unknown Source)
	              at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	              at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	              at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	              at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
	              at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	              at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	              at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	              at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	              at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	              at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	              at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:151)
	              at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
	              at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
	              at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialFactory$ComputeCredentialWithRetry.executeRefreshToken(CredentialFactory.java:192)
	              at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:470)
	              at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialFactory.getCredentialFromMetadataServiceAccount(CredentialFactory.java:247)
	              ... 30 more
              22/12/13 11:21:31 WARN FileSystem: Failed to initialize fileystem gs://gcp-public-data-landsat/index.csv.gz: java.io.IOException: Error getting access token from metadata server at: http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token

Motivation for fix:
Being able to read public access data from GCS with spark using this connector would be beneficial to alot of developers I assume.

**Comment by medb** [comment]
In older GCS connector versions this is also supported. Refer to tests to see how to use it via `fs.gs.auth.service.account.enable=false` and `fs.gs.auth.null.enable=true` properties: https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/3fd491a80aeb7f9d68fe6beb8c1a9cd4c90e9f63/gcs/src/test/java/com/google/cloud/hadoop/fs/gcs/GoogleHadoopFileSystemIntegrationTest.java#L1170-L1193

**Comment by nicojord** [comment]
> In older GCS connector versions this is also supported. Refer to tests to see how to use it via `fs.gs.auth.service.account.enable=false` and `fs.gs.auth.null.enable=true` properties:
> 
> https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/3fd491a80aeb7f9d68fe6beb8c1a9cd4c90e9f63/gcs/src/test/java/com/google/cloud/hadoop/fs/gcs/GoogleHadoopFileSystemIntegrationTest.java#L1170-L1193

Thank You @medb , I can confirm this is solution works, tested and working exactly as expected. Might be a good idea to add a section related to this configuration in the docs.
