### ISSUE TITLE
Unauthorized access on gRPC via DirectPath have issues

### ISSUE THREAD

**Issue by singhravidutt** [GoogleCloudDataproc/hadoop-connectors#998]
Upgrading to v2.22.0 of java-storage caused 2 Unit tests to fail

[ERROR] GoogleCloudStorageFileSystemTest.testConstructor:138 » NullPointer creds [ERROR] GoogleCloudStorageFileSystemTest.testClientType:120 » NullPointer creds

Both of the test use GoogleCredential with null access token (unauthorised access). Things seems to have worked fine till v2.17.0 but upgrading to v2.22.0 started causing failures. Even using NoCredential causes exception while creating Storage client.

```
[ERROR] com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystemTest.testConstructor[1]  Time elapsed: 0.028 s  <<< ERROR!
java.lang.NullPointerException: creds
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
	at io.grpc.auth.GoogleAuthLibraryCallCredentials.<init>(GoogleAuthLibraryCallCredentials.java:74)
	at io.grpc.auth.GoogleAuthLibraryCallCredentials.<init>(GoogleAuthLibraryCallCredentials.java:69)
	at io.grpc.auth.MoreCallCredentials.from(MoreCallCredentials.java:35)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:324)
	at com.google.api.gax.grpc.ChannelPool.<init>(ChannelPool.java:105)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:83)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:236)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:230)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:201)
	at com.google.storage.v2.stub.GrpcStorageStub.create(GrpcStorageStub.java:505)
	at com.google.storage.v2.stub.StorageStubSettings.createStub(StorageStubSettings.java:605)
	at com.google.storage.v2.StorageClient.<init>(StorageClient.java:165)
	at com.google.storage.v2.StorageClient.create(StorageClient.java:148)
	at com.google.cloud.storage.GrpcStorageOptions$GrpcStorageFactory.create(GrpcStorageOptions.java:581)
	at com.google.cloud.storage.GrpcStorageOptions$GrpcStorageFactory.create(GrpcStorageOptions.java:546)
```

**Comment by singhravidutt** [comment]
Fixed now.
